version: '3.3'


services:
  mysql:
    image: mysql:5.7.37
    ports:
      - '3306:3306'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=chatgpt_lsp
      - MYSQL_PASSWORD=chatgpt_lsp
      - MYSQL_DATABASE=chatgpt_lsp
  redis:
    image: redis:5.0.14
    ports:
      - 6379:6379
    command: redis-server --requirepass lsp123456